### ISSUE TITLE
Testnet3 tracking issue

### ISSUE THREAD

**Issue by Schwartz10** [glifio/wallet#395]
Syncing: 
This is one of a few issues, including a memory spike issue causing the node to crash
https://github.com/filecoin-project/lotus/issues/1546

Handling gas:
Lotus testnet3 local net gas estimation broken: https://github.com/filecoin-project/lotus/issues/1548
- I think this should fix it, but will wait to pull this in until we know for sure: https://github.com/openworklabs/filecoin-wallet-provider/pull/16

ledger-app:
https://github.com/Zondax/ledger-filecoin/issues/40

wasm signing library:
https://github.com/Zondax/filecoin-rs/issues/124

**Comment by Schwartz10** [comment]
Update:

**Filecoin message**
- [x] https://github.com/openworklabs/filecoin-message/issues/12
- [x] Merge https://github.com/openworklabs/filecoin-message/pull/13 when ready
- [x] Bump package.json version and publish to npm

**Lotus jsonrpc engine**
- [x] Merge https://github.com/openworklabs/lotus-jsonrpc-engine/pull/5 when ready
- [x] Bump package.json version and publish to npm

**Filecoin-wallet-provider**
- [x] Merge https://github.com/openworklabs/filecoin-wallet-provider/pull/17 when ready

**Filecoin-web-wallet**
- [ ] Fix failing tests/snapshots
- [ ] add tests for new wasm handling
- [ ] Pin new versions in package.json
- [ ] Wait for zondax to publish new version
- [ ] https://github.com/openworklabs/filecoin-web-wallet/issues/410
- [ ] https://github.com/openworklabs/filecoin-web-wallet/issues/88
- [ ] Sort out solution for HTTPS and JWT for the hosted node (can we just update the pointer on proxy.openworklabs.com?)
